### ISSUE TITLE
Fade while only in a group?

### ISSUE THREAD

**Issue by Baz4k** [zaCade/FadeObjectiveTracker#1]
Is there a way to make this only fade while in a group? I wasn't sure where to actually ask this, sorry if this is the wrong place.

**Comment by zaCade** [comment]
No worries, its the right place.

But at the moment the addon doesnt check if you are in a group or not.
However, if you want it added. I can add it, youll just need to describe how you'd want it to function, and ill see what i can do.

**Comment by Baz4k** [comment]
Thanks, that's awesome! I currently am using Keliel's tracker. This fades that, but it doesn't seem to fade the top bar. (If you could fix that that would be awesome, too!)  I have details and the tracker in the same place. I only need details when I am in a group and in combat. 

Maybe if you added a check block under the "Extras" section of your settings that said "Only fade while in a group" and when that was checked it would never fade while not in a group that would be great. Also, where can I send you donations? Thanks for all of the hard work!

**Comment by zaCade** [comment]
Added the only in group toggle, did also take a look at the tracker addon you mentioned.
Sadly that addon doesn't parent to the tracker in any way, so i'd have to add support for that addon in specific. Which i'd rather not do, since i'd prefer to make the functionality work for all/multiple addons at once if i do something like this.
As for donations, i appriciate the fact you want to donate but thats entirely not needed. This stuff is simply a thing i do on the side :)

If you find any bugs, just feel free to open up another issue.
